name: 'Label Actions'

on:
  workflow_call:

permissions:
  contents: read
  issues: write
  pull-requests: write
  discussions: write

jobs:
  lock:
    if: ${{ (github.event.label.name == 'spam') && (github.event.action == 'labeled') }}
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/close-issue@v2
        with: 
          close-reason: 'not_planned'
        if: ${{ github.event_name == 'issue' }}
      - uses: OSDKDev/lock-issues@v1.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
