name: 'Label Actions'

on:
  workflow_call:

permissions:
  contents: read
  issues: write
  pull-requests: write
  discussions: write

jobs:
  lock:
    if: ${{ (github.event.label.name == 'spam') && (github.event.action == 'labeled') }}
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/close-issue@v2
        name: Close Issue
        with: 
          close-reason: 'not_planned'
        if: ${{ github.event_name != 'pull_request' }}
      - uses: peter-evans/close-issue@v2
        name: Close PR
        if: ${{ github.event_name == 'pull_request' }}
      - uses: maxkomarychev/oction-lock-issue@v0.7.1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          issue_number: ${{ github.event.number }}
