name: 'Label Actions'

on:
  workflow_call:

permissions:
  contents: read
  issues: write
  pull-requests: write
  discussions: write

jobs:
  action:
    if: ${{ github.event.label.name == 'spam' }}
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/close-issue@v2
        with: 
          close-reason: 'not_planned'
      - uses: OSDKDev/lock-issues@v1.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
