name: 'PR creation'

on:
  workflow_call:
    secrets:
      GH_APP_NAME:
        required: true
      GH_APP_KEY:
        required: true

permissions:
  contents: read
  issues: write
  pull-requests: write
  discussions: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: triage
      - name: Generate Token
        id: generate_token
        uses: jarylc/github-app-token@v3.0.1
        with:
          app: ${{ secrets.GH_APP_NAME }}
          key: ${{ secrets.GH_APP_KEY }}
      - name: Create PR review request
        run: |
          gh pr edit ${{ github.event.pull_request.html_url }} \
              --add-reviewer forgeforce/triagers
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
