name: 'PR creation'

on:
  workflow_call:

permissions:
  contents: read
  issues: write
  pull-requests: write
  discussions: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: triage
      - name: Create PR review request
        run: |
          gh pr edit ${{ github.event.pull_request.html_url }} \
              --add-reviewer forgeforce/triagers
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
