name: 'PR creation'

on:
  workflow_call:
    secrets:
      GH_APP_NAME:
        required: true
      GH_APP_KEY:
        required: true

permissions:
  contents: read
  issues: write
  pull-requests: write
  discussions: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: navikt/github-app-token-generator@v1
        id: generate_token
        with:
          private-key: ${{ secrets.GH_APP_KEY }}
          app-id: ${{ secrets.GH_APP_NAME }}
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: triage
          github_token: ${{ steps.generate_token.outputs.token }}
      - name: Create PR review request
        run: |
          gh pr edit ${{ github.event.pull_request.html_url }} \
              --add-reviewer forgeforce/triagers
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
      - uses: monry/actions-add-issue-to-project@v2
        with:
          project-url: https://github.com/orgs/ForgeForce/projects/4
          github-token: ${{ steps.generate_token.outputs.token }}
