on:
  workflow_call:
    secrets:
      GH_APP_NAME:
        required: true
      GH_APP_KEY:
        required: true
        
permissions:
  contents: read
  issues: write
  pull-requests: write
  discussions: write
 
name: Slash commands
jobs:
  check_comments:
    name: Check comments for /assign
    runs-on: ubuntu-latest
    steps:
      - uses: navikt/github-app-token-generator@v1
        id: generate_token
        with:
          private-key: ${{ secrets.GH_APP_KEY }}
          app-id: ${{ secrets.GH_APP_NAME }}
      - uses: forgeforce/forgecommands@a8b4e16c3f9feb423aed4456ebee46fc407730ec
        with:
          prefix: "@forgeforce-bot<ws>"
          github-token: ${{ steps.generate_token.outputs.token }}
