on:
  workflow_call:
    secrets:
      GH_APP_NAME:
        required: true
      GH_APP_KEY:
        required: true
        
permissions:
  contents: read
  issues: write
  pull-requests: write
  discussions: write
 
name: Slash commands
jobs:
  check_comments:
    name: Check comments for /assign
    runs-on: ubuntu-latest
    steps:
      - uses: navikt/github-app-token-generator@v1
        id: generate_token
        with:
          private-key: ${{ secrets.GH_APP_KEY }}
          app-id: ${{ secrets.GH_APP_NAME }}
      - name: Check for Command
        id: command
        uses: xt0rted/slash-command-action@v1
        with:
          repo-token: ${{ steps.generate_token.outputs.token }}
          command: assign
          reaction: "true"
          reaction-type: "eyes"
          allow-edits: "false"
      - uses: TheModdingInquisition/actions-team-membership@v1.0
        with:
          comment: "You cannot use this command."
          team: 'triagers'
          token: ${{ steps.generate_token.outputs.token }}
          exit: false
      - name: 'Auto-assign issue'
        if: ${{ (steps.command.outputs.command-arguments != '') && (steps.command.outputs.command-arguments != ' ') }}
        uses: pozil/auto-assign-issue@v1
        with:
          removePreviousAssignees: true
          teams: ${{ steps.command.outputs.command-arguments }}
          repo-token: ${{ steps.generate_token.outputs.token }}
          allowSelfAssign: false
      - name: Create comment
        if: ${{ (steps.command.outputs.command-arguments == '') || (steps.command.outputs.command-arguments == ' ') }}
        uses: jungwinter/comment@v1
        with:
          type: create
          body: "Please provide a team to assign"
          issue_number: ${{ github.event.number }}
          token: ${{ steps.generate_token.outputs.token }}
